version: "3.8"
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile.node
    container_name: client
    volumes:
      - ./:/var/www/
      - /var/www/node_modules
volumes:
  mysql_data: